/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bet {
  'memberId' : Principal,
  'numberBets' : Array<NumberBet>,
  'roundId' : bigint,
  'timestamp' : bigint,
}
export interface GameRound {
  'id' : bigint,
  'status' : { 'closed' : null } |
    { 'open' : null } |
    { 'declared' : null },
  'winningNumber' : [] | [bigint],
  'createdAt' : bigint,
  'roundName' : string,
}
export interface NumberBet { 'number' : bigint, 'amount' : bigint }
export interface RoundResult {
  'winningNumber' : bigint,
  'winnerId' : [] | [Principal],
  'roundId' : bigint,
  'allWinnerCandidates' : Array<Bet>,
  'winnerBetAmount' : bigint,
  'winnerPayout' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'closeRound' : ActorMethod<[bigint], undefined>,
  'createRound' : ActorMethod<[string], bigint>,
  'declareWinner' : ActorMethod<[bigint, bigint], undefined>,
  'getAllBetsForRound' : ActorMethod<[bigint], Array<Bet>>,
  'getAllRounds' : ActorMethod<[], Array<GameRound>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentRound' : ActorMethod<[], [] | [GameRound]>,
  'getMyBets' : ActorMethod<[bigint], Array<Bet>>,
  'getRoundResult' : ActorMethod<[bigint], [] | [RoundResult]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeBets' : ActorMethod<[bigint, Array<NumberBet>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];