/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NumberBet = IDL.Record({ 'number' : IDL.Nat, 'amount' : IDL.Nat });
export const Bet = IDL.Record({
  'memberId' : IDL.Principal,
  'numberBets' : IDL.Vec(NumberBet),
  'roundId' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const GameRound = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'declared' : IDL.Null,
  }),
  'winningNumber' : IDL.Opt(IDL.Nat),
  'createdAt' : IDL.Int,
  'roundName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RoundResult = IDL.Record({
  'winningNumber' : IDL.Nat,
  'winnerId' : IDL.Opt(IDL.Principal),
  'roundId' : IDL.Nat,
  'allWinnerCandidates' : IDL.Vec(Bet),
  'winnerBetAmount' : IDL.Nat,
  'winnerPayout' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'closeRound' : IDL.Func([IDL.Nat], [], []),
  'createRound' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'declareWinner' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getAllBetsForRound' : IDL.Func([IDL.Nat], [IDL.Vec(Bet)], ['query']),
  'getAllRounds' : IDL.Func([], [IDL.Vec(GameRound)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentRound' : IDL.Func([], [IDL.Opt(GameRound)], ['query']),
  'getMyBets' : IDL.Func([IDL.Nat], [IDL.Vec(Bet)], ['query']),
  'getRoundResult' : IDL.Func([IDL.Nat], [IDL.Opt(RoundResult)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeBets' : IDL.Func([IDL.Nat, IDL.Vec(NumberBet)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NumberBet = IDL.Record({ 'number' : IDL.Nat, 'amount' : IDL.Nat });
  const Bet = IDL.Record({
    'memberId' : IDL.Principal,
    'numberBets' : IDL.Vec(NumberBet),
    'roundId' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const GameRound = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'closed' : IDL.Null,
      'open' : IDL.Null,
      'declared' : IDL.Null,
    }),
    'winningNumber' : IDL.Opt(IDL.Nat),
    'createdAt' : IDL.Int,
    'roundName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RoundResult = IDL.Record({
    'winningNumber' : IDL.Nat,
    'winnerId' : IDL.Opt(IDL.Principal),
    'roundId' : IDL.Nat,
    'allWinnerCandidates' : IDL.Vec(Bet),
    'winnerBetAmount' : IDL.Nat,
    'winnerPayout' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'closeRound' : IDL.Func([IDL.Nat], [], []),
    'createRound' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'declareWinner' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getAllBetsForRound' : IDL.Func([IDL.Nat], [IDL.Vec(Bet)], ['query']),
    'getAllRounds' : IDL.Func([], [IDL.Vec(GameRound)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentRound' : IDL.Func([], [IDL.Opt(GameRound)], ['query']),
    'getMyBets' : IDL.Func([IDL.Nat], [IDL.Vec(Bet)], ['query']),
    'getRoundResult' : IDL.Func([IDL.Nat], [IDL.Opt(RoundResult)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeBets' : IDL.Func([IDL.Nat, IDL.Vec(NumberBet)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };